name: Sh Validador
on:
  push:
    branches:
      - main
jobs:
  shellcheck:
    
    runs-on: ubuntu-latest

    steps:
       uses: actions/checkout@v3

       run: sudo apt-get install -y shellcheck

       run: |
          echo "Ejecutando ShellCheck..."
          shopt -s globstar nullglob
          files=(**/*.sh)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No hay archivos .sh "
            exit 0
          fi
          shellcheck "${files[@]}"

